[package]
name = "zrdds"
version = "0.1.0"
edition = "2024"
authors = ["Your Name <your.email@example.com>"]
description = "Rust bindings for ZRDDS"
license = "MIT OR Apache-2.0"
repository = "https://github.com/yourusername/zrdds"
keywords = ["dds", "real-time", "messaging", "distributed"]
categories = ["network-programming", "api-bindings"]
readme = "README.md"

[lib]
name = "zrdds"
path = "src/lib.rs"

[[example]]
name = "basic_usage"
path = "examples/basic_usage.rs"

[dependencies]
eframe = "0.27"
egui = "0.27"
libc = "0.2"
serde_json = "1.0.143"
whoami = "1.3" 
scrap = "0.5.0"
image = "0.24"
base64 = "0.21"
once_cell = "1.21.3"
yuv = "0.8.6"
openh264 = "0.4.1"
parking_lot = "0.12.1"
thiserror = "1.0"
rfd = "0.11"
chrono = "0.4"

[build-dependencies]
cc = "1.0"
bindgen = "0.72"
glob = "0.3.3"
